export const GET_VISITORS_LIST = 'GET_VISITORS_LIST';
export const USER_LOGIN = 'USER_LOGIN';
export const SET_USER_SESSION = 'SET_USER_SESSION';
export const GET_USER_SESSION = 'SET_USER_SESSION';
export const CLEAR_USER_SESSION = 'CLEAR_USER_SESSION';
